FROM node:22.14 AS base

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM node:22.14-alpine3.21 AS deploy

USER 1000

WORKDIR /usr/src/app
COPY --from=base /usr/src/app/dist ./dist
COPY --from=base /usr/src/app/node_modules ./node_modules
COPY --from=base /usr/src/app/package.json ./package.json

EXPOSE 3333

ENTRYPOINT [ "./.docker/startup.sh" ]