services:
  db:
    image: postgres
    restart: always
    shm_size: 512mb
    ports:
      - 5434:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: silvajoao/plathanus:latest
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data: