services:
  db:
    image: postgres
    restart: always
    shm_size: 512mb
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  db_test:
    image: postgres
    restart: always
    shm_size: 512mb
    env_file:
      - .env.test
    ports:
      - 5433:5432

volumes:
  db_data: