services:
  db:
    image: postgres
    restart: always
    shm_size: 512mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: plathanus
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  db_test:
    image: postgres
    restart: always
    shm_size: 512mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: plathanus_test
    ports:
      - 5433:5432

volumes:
  db_data: