services:
  db:
    image: postgres
    restart: always
    shm_size: 512mb
    ports:
      - 5434:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - plathanus_network

  api:
    image: silvajoao/plathanus:latest
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - plathanus_network

volumes:
  db_data:

networks:
  plathanus_network:
    driver: bridge