services:
  db:
    image: postgres
    restart: always
    shm_size: 512mb
    ports:
      - 5434:5432
  
  api:
    build:
      context: .
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - db
    env_file:
      - .env