name: deploy

on:
    push:
        branches:
        - main

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Build docker image to scan for vulnerabilities
          uses: docker/build-push-action@v2
          with:
            context: .
            file: Dockerfile-prod
            load: true
            tags: ${{ secrets.DOCKER_USERNAME }}/api-plathanus:scan
            cache-from: type=gha
            cache-to: type=gha,mode=max

        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.28.0
          with:
            image-ref: '${{ secrets.DOCKER_USERNAME }}/api-plathanus:scan'
            format: 'table'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
            
        - name: Build, tag, and push docker image to Docker Hub
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            cache-from: type=gha
            tags: ${{ secrets.DOCKER_USERNAME }}/plathanus:latest
